# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b14a04129843d23117bc0f5601a49fec95e2d6f5e85ec3fa3c8523fedad01c7a8e25187b5913ca957420443c50d5f97c254e6f16779e4c88652d400abe70b52

test:
  secret_key_base: 18746731fa4e1de0471426ef630971c92cef5073815120ebc8755113b355812f8ad58e1c18940c7bcfc1b1e9ac60a308db9acb10c803a04072656a55dd6cbb7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
